/** @type {import('tailwindcss').Config} */
// "Obsidian Edit" design system — tokens copied from the Stitch reference
// (stitch_custom_editing_studio). Pro video-editor theme: near-black surfaces,
// electric-purple primary, orange caption accents, blue audio accents.
export default {
  content: ['./index.html', './**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131315',
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#201f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface-variant': '#353437',
        'on-background': '#e5e1e4',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#c7c4d6',
        outline: '#918f9f',
        'outline-variant': '#464554',
        primary: '#c2c1ff',
        'primary-container': '#5856d6',
        'on-primary': '#1c0b9f',
        'on-primary-container': '#e7e4ff',
        'inverse-primary': '#4f4ccd',
        secondary: '#adc6ff',
        'secondary-container': '#4b8eff',
        'on-secondary-container': '#00285c',
        'on-secondary-fixed-variant': '#004493',
        'secondary-fixed': '#d8e2ff',
        tertiary: '#ffb785',
        'tertiary-container': '#a25100',
        'on-tertiary-container': '#ffe1cf',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '12px',
        'panel-padding': '16px',
        'timeline-track-height': '48px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'mono-label': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'mono-label': ['12px', {lineHeight: '16px', fontWeight: '500'}],
        'body-md': ['14px', {lineHeight: '20px', fontWeight: '400'}],
        'body-sm': ['12px', {lineHeight: '16px', fontWeight: '400'}],
        'headline-lg': ['24px', {lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600'}],
        'headline-md': ['18px', {lineHeight: '24px', fontWeight: '600'}],
        'label-bold': ['11px', {lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '700'}],
      },
    },
  },
  plugins: [],
};
